# Generated by Django 5.2.1 on 2025-05-20 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myinvest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "localizacao",
                    models.CharField(max_length=200, verbose_name="Localização"),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Preço"
                    ),
                ),
                (
                    "status_obra",
                    models.CharField(
                        choices=[
                            ("planta", "Na planta"),
                            ("construcao", "Em construção"),
                            ("finalizado", "Finalizado"),
                        ],
                        max_length=20,
                        verbose_name="Status da Obra",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Cadastro",
                    ),
                ),
                (
                    "corretor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imoveis",
                        to="myinvest.corretor",
                    ),
                ),
            ],
        ),
    ]
