# Generated by Django 5.2.1 on 2025-05-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myinvest", "0002_imovel"),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoImovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="imoveis_fotos/", verbose_name="Imagem"
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="myinvest.imovel",
                    ),
                ),
            ],
        ),
    ]
