# Generated by Django 5.2.1 on 2025-06-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myinvest", "0004_imovel_disponivel_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="imoveis",
            field=models.ManyToManyField(related_name="clientes", to="myinvest.imovel"),
        ),
    ]
