# Generated by Django 5.2.1 on 2025-06-08 14:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinvest', '0005_cliente_imoveis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='preferencias',
            field=models.JSONField(blank=True, default=dict, verbose_name='Preferências de Busca'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='receber_notificacoes',
            field=models.BooleanField(default=True, verbose_name='Receber Notificações'),
        ),
        migrations.AddField(
            model_name='corretor',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='corretor',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='fotoimovel',
            name='legenda',
            field=models.CharField(blank=True, max_length=100, verbose_name='Legenda'),
        ),
        migrations.AddField(
            model_name='fotoimovel',
            name='principal',
            field=models.BooleanField(default=False, verbose_name='Foto Principal'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='anunciado_por_cliente',
            field=models.BooleanField(default=False, verbose_name='Anunciado por Cliente'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Área Total (m²)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='banheiros',
            field=models.IntegerField(default=0, verbose_name='Número de Banheiros'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cliente_anunciante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis_anunciados', to='myinvest.cliente'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_previsao_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='progresso_obra',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progresso da Obra (%)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='quartos',
            field=models.IntegerField(default=0, verbose_name='Número de Quartos'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_imovel',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('comercial', 'Comercial'), ('terreno', 'Terreno')], default='casa', max_length=20, verbose_name='Tipo de Imóvel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='vagas_garagem',
            field=models.IntegerField(default=0, verbose_name='Vagas de Garagem'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status_obra',
            field=models.CharField(choices=[('planta', 'Na planta'), ('fundacao', 'Fundação'), ('estrutura', 'Estrutura'), ('acabamento', 'Acabamento'), ('finalizado', 'Finalizado')], max_length=20, verbose_name='Status da Obra'),
        ),
        migrations.CreateModel(
            name='AnuncioImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='myinvest.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='CronogramaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=100, verbose_name='Fase')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='myinvest.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('obra', 'Atualização de Obra'), ('novo_imovel', 'Novo Imóvel'), ('status', 'Mudança de Status')], max_length=20, verbose_name='Tipo de Notificação')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myinvest.imovel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('dados', models.JSONField(verbose_name='Dados do Relatório')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='myinvest.corretor')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
